export enum ActionViewType {
  RECORD_TABLE_BULK_SELECTION = 'RECORD_TABLE_BULK_SELECTION',
  RECORD_BOARD_BULK_SELECTION = 'RECORD_BOARD_BULK_SELECTION',
  RECORD_TABLE_SINGLE_RECORD_SELECTION = 'RECORD_TABLE_SINGLE_RECORD_SELECTION',
  RECORD_BOARD_SINGLE_RECORD_SELECTION = 'RECORD_BOARD_SINGLE_RECORD_SELECTION',
  RECORD_TABLE_NO_SELECTION = 'RECORD_TABLE_NO_SELECTION',
  RECORD_BOARD_NO_SELECTION = 'RECORD_BOARD_NO_SELECTION',
  SHOW_PAGE = 'SHOW_PAGE',
}
