name: CI Tinybird
on:
  push:
    branches:
      - main

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    uses: tinybirdco/ci/.github/workflows/ci.yml@main
    steps:
      - name: Check for changed files
        id: changed-files
        uses: tj-actions/changed-files@v11
        with:
          files: |
            package.json
            packages/twenty-tinybird/**

      - name: Skip if no relevant changes
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No relevant changes. Skipping CI."

      - name: Check twenty-tinybird package
        with:
          data_project_dir: packages/twenty-tinybird
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}
          tb_host: https://api.eu-central-1.aws.tinybird.co
