name: CI Website
on:
  push:
    branches:
      - main

  pull_request:
    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  website-build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    services:
      postgres:
        image: twentycrm/twenty-postgres-spilo
        env:
          PGUSER_SUPERUSER: postgres
          PGPASSWORD_SUPERUSER: twenty
          ALLOW_NOSSL: "true"
          SPILO_PROVIDER: "local"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changed files
        id: changed-files
        uses: tj-actions/changed-files@v11
        with:
          files: 'package.json, packages/twenty-website/**'

      - name: Install dependencies
        if: steps.changed-files.outputs.changed == 'true' 
        uses: ./.github/workflows/actions/yarn-install

      - name: Server / Create DB
        if: steps.changed-files.outputs.any_changed == 'true'
        run: PGPASSWORD=twenty psql -h localhost -p 5432 -U postgres -d postgres -c 'CREATE DATABASE "default";'

      - name: Website / Run migrations
        if: steps.changed-files.outputs.changed == 'true' 
        run: npx nx database:migrate twenty-website 
        env:
          DATABASE_PG_URL: postgres://postgres:twenty@localhost:5432/default
      - name: Website / Build Website
        if: steps.changed-files.outputs.changed == 'true' 
        run: npx nx build twenty-website
        env:
          DATABASE_PG_URL: postgres://postgres:twenty@localhost:5432/default

      - name: Mark as VALID
        if: steps.changed-files.outputs.changed != 'true'  # If no changes, mark as valid
        run: echo "No relevant changes detected. CI is valid."    